# Generated by Django 4.1.3 on 2022-11-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.AlterModelOptions(name="category", options={"ordering": ("name",)},),
        migrations.AlterModelOptions(
            name="product", options={"ordering": ("-date_added",)},
        ),
    ]
